# Generated by Django 5.2.14 on 2026-05-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=128)),
                ('otp', models.CharField(max_length=6)),
                ('otp_created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(max_length=10)),
                ('full_name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('mobile_number', models.CharField(max_length=15)),
                ('qualification', models.CharField(blank=True, max_length=200, null=True)),
                ('specialization', models.CharField(blank=True, max_length=200, null=True)),
                ('practicing_year_from', models.IntegerField(blank=True, null=True)),
                ('license_number', models.CharField(blank=True, max_length=200, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='google_access_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='google_refresh_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='google_token_expiry',
        ),
        migrations.AddField(
            model_name='user',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='license_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='practicing_year_from',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='qualification',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='specialization',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('doctor', 'Doctor'), ('patient', 'Patient')], max_length=10),
        ),
    ]
