# Generated by Django 4.2.13 on 2026-05-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_booking_slot_alter_booking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='doctor_calendar_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='patient_calendar_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
