# Generated by Django 5.2.14 on 2026-05-19 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_booking_slot_alter_booking_status_and_more'),
        ('doctors', '0002_alter_availabilityslot_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AvailabilitySlot',
        ),
        migrations.DeleteModel(
            name='DoctorProfile',
        ),
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('doctor', 'date', 'start_time', 'end_time')},
        ),
    ]
